import { Inter } from "next/font/google";
import "./globals.css";
import "./app.css";
import Call from "@/components/call/Call";
import ContactForm from "@/components/call/ContactForm";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
          {children}
        <Call />
        <ContactForm />
        <Footer />
      </body>
    </html>
  );
}
